### PR TITLE
feat(labels/apps): add YellowNetwork contracts

### PR DESCRIPTION
**Pull request by nksazonov**
Hi!
We have been using BundlerBear for quite some time! It is awesome!
We would like to add more information about our project, so that the data displayed is more accurate. This is crucial for us as we focus on AA Accounts.
If needed, we can collaborate more.

### CODE REVIEW

**Comment by Jam516** [comment]
thanks for the submission. 

one change: please make the addresses lowercase

once you do that, I will accept the PR

**Comment by nksazonov** [comment]
@Jam516 , done

**Comment by Jam516** [comment]
thanks, changes will reflect on the website after a day

so do you work at both layer3 (saw in your bio) and yellow network?

**Comment by nksazonov** [comment]
Thanks!
YellowNetwork is the company behind the layer-3 clearing protocol, which you can see at https://github.com/layer-3/clearsync.
Now we are focusing more on a user acquisition, user experience, account abstraction and load-testing. Our main product for now is Yellow Vault - AA Wallet. See more at: https://yellow.com/vault

**Pull request merged**
